### ISSUE TITLE
Quartz.net configuration wrapping issues

### ISSUE THREAD

**Issue by ivan-brko** [ivan-brko/Quartz.FSharp#4]
This task is used to track all issues with wrapping of quartz.net configuration.

- [ ] Thread count is limited to max 20. Should this be configured differently?
- [ ] At the moment only 2 quartz.net configurations are configurable through the wrapper, use this task to track adding the rest as needed
- [ ] Remove the option to change/add options in the Quartz.Net directly (through function `Configuration.SetKeyValue`) by adding all the needed configurations as separate functions
